Catch the connection time out error in retry loop
The logic was there to limit to only 3 tries, but only if the right
exceptions were caught. A snippet of the output from
[the problematic Ops Jenkins job][0] is pasted below.

Because the connection time out exception was not one of the exceptions
that is caught, it was passed up to the caller of `#get_results`, which
can be traced to `SearchSolrTools::Harvesters::Oai#harvest`. The code
there is designed to work with a resumption token, and will attempt to
get the results until the resumption token is nil or empty, *rescuing
any exception at all*. This is why multiple retries were happening
despite logic being present to only allow for 3 tries.

Add tests to ensure exactly 3 tries are attempted in the case of each
kind of error we expect to encounter.

[0]: https://ops.nsidc.org/jenkins/job/Search-Solr_Harvest/DATA_CENTER=pdc,ENVIRONMENT=production/72/console

pdc
Running SearchSolrTools::Harvesters::Pdc at http://www.polardata.ca/oai/provider
Request: http://www.polardata.ca/oai/provider?verb=ListRecords&metadataPrefix=iso
ERROR: Connection timed out - connect(2) for "www.polardata.ca" port 80
Request: http://www.polardata.ca/oai/provider?verb=ListRecords&metadataPrefix=iso
ERROR: Connection timed out - connect(2) for "www.polardata.ca" port 80
Request: http://www.polardata.ca/oai/provider?verb=ListRecords&metadataPrefix=iso
ERROR: Connection timed out - connect(2) for "www.polardata.ca" port 80
Request: http://www.polardata.ca/oai/provider?verb=ListRecords&metadataPrefix=iso
ERROR: Connection timed out - connect(2) for "www.polardata.ca" port 80
Request: http://www.polardata.ca/oai/provider?verb=ListRecords&metadataPrefix=iso
ERROR: Connection timed out - connect(2) for "www.polardata.ca" port 80