Fix broken delete_all commands
`SolrEnvironments` was not properly namespaced, and the method `sh` is
undefined outside of Rake.

========================================================================

Output showing namespace issue:

vagrant@vwintryigloo:/opt/search-solr-tools$ bundle exec search_solr_tools delete_all --environment=local
/opt/search-solr-tools/bin/search_solr_tools:33:in `delete_all': uninitialized constant SolrHarvestCLI::SolrEnvironments (NameError)
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/search-solr-tools/bin/search_solr_tools:87:in `<top (required)>'
        from /var/lib/gems/1.9.1/bin/search_solr_tools:23:in `load'
        from /var/lib/gems/1.9.1/bin/search_solr_tools:23:in `<main>'

========================================================================

Output showing NoMethodError:

vagrant@vwintryigloo:/opt/search-solr-tools$ bundle exec search_solr_tools delete_all --environment=local
/opt/search-solr-tools/bin/search_solr_tools:34:in `delete_all': undefined method `sh' for #<SolrHarvestCLI:0x000000013c57c0> (NoMethodError)
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/search-solr-tools/bin/search_solr_tools:87:in `<top (required)>'
        from /var/lib/gems/1.9.1/bin/search_solr_tools:23:in `load'
        from /var/lib/gems/1.9.1/bin/search_solr_tools:23:in `<main>'